Better error checking and overall code quality

diff --git a/lightshot_print_screen b/lightshot_print_screen
--- a/lightshot_print_screen
+++ b/lightshot_print_screen
@@ -1,15 +1,7 @@
 #!/bin/sh
 
-# treat unset variables as an error when substituting
-set -o nounset
-
-#------------------------------------------------------------------------------
-
-# these constants aim on fast script identification
-readonly script_name_executable=$(basename "${0}")
-readonly script_name_human_friendly='Lightshot Print Screen key Linux handler'
-readonly script_version='1.0'
-readonly script_github_url='https://git.io/fx2US'
+# exit script if it tries to use undeclared variables
+set -u
 
 #------------------------------------------------------------------------------
 
@@ -21,66 +13,121 @@ hotkey='Print'
 
 #------------------------------------------------------------------------------
 
-print_error_and_exit()
-# expected arguments:
-# $1 = error origin
-# $2 = error message
-{
-    # redirect all output from this function to standard error stream
-    exec 1>&2
-
-    # check if exactly 2 arguments have been passed
-    # if not, print out an input check error without colors
-    if [ "${#}" -ne 2 ]
-    then
-        # $1 and $2 are to be shown literally in this message
-        # link to wiki: https://github.com/koalaman/shellcheck/wiki/SC2016
-        # shellcheck disable=SC2016
-        printf 'print_error_and_exit() input check\n\n\tWrong number of arguments has been passed: %s!\n\tExpected the following 2:\n\t\t$1 - error origin\n\t\t$2 - error message\n' "${#}"
-        exit 1
-    fi
-
-    if command -v tput > /dev/null 2>&1 &&
-       tput bold > /dev/null 2>&1 &&
-       tput setaf 1 > /dev/null 2>&1
-    then
-        # color definitions
-        readonly bold_yellow=$(tput bold)$(tput setaf 3)
-        readonly bold_red=$(tput bold)$(tput setaf 1)
-        readonly reset_color=$(tput sgr0)
-        # here we have color support, so we make:
-        # - error origin in yellow color
-        # - error message in default color
-        # - error statement in red color
-        printf '%s\n\n\t%b\n\n%s\n' \
-            "${bold_yellow}${1}${reset_color}" \
-            "${2}" \
-            "${bold_red}An error occurred, see above.${reset_color}"
-    else
-        # here we do not have color support
-        printf '%s\n\n\t%b\n\n%s\n' \
-            "${1}" \
-            "${2}" \
-            "An error occurred, see above."
-    fi
-
-    # always exit the script with the usual exit code 1
-    exit 1
-}
+# these constants aim on fast script identification
+readonly script_name_executable=$( basename "$0" )
+readonly script_name_human_friendly='Lightshot Print Screen key Linux handler'
+readonly script_version='2.0'
+readonly script_github_url='https://git.io/fx2US'
 
 #------------------------------------------------------------------------------
 
-# do not warn that no caller passes arguments - that is the point of the test
-# link to wiki: https://github.com/koalaman/shellcheck/wiki/SC2120
-# shellcheck disable=SC2120
-am_i_root()
-# expected arguments: none
+tput_colors_supported ()
+## bool function - getter of the terminal color support
+# if true, then this code defines global color constants
 {
-    # check if no argument has been passed
-    [ "${#}" -eq 0 ] || print_error_and_exit "am_i_root() input check" "Some arguments have been passed to the function!\\n\\tNo arguments expected.\\n\\tPassed: ${*}"
+    command -v tput && tput bold && [ "$(tput colors)" -ge 8 ]
+} > \
+/dev/null 2>&1
 
-    # check if the user is root
-    # this returns an exit code of the command directly
+if tput_colors_supported; then
+
+    # tput special sequences
+#    number_of_colors=$(tput colors)
+    color_reset=$(tput sgr0)
+    bold_text=$(tput bold)
+
+    # definitions of basic colors with bold test
+    color_red=${bold_text}$(tput setaf 1)
+#    color_green=${bold_text}$(tput setaf 2)
+    color_yellow=${bold_text}$(tput setaf 3)
+#    color_blue=${bold_text}$(tput setaf 4)
+#    color_magenta=${bold_text}$(tput setaf 5)
+#    color_cyan=${bold_text}$(tput setaf 6)
+#    color_white=${bold_text}$(tput setaf 7)
+
+else
+
+#    number_of_colors=0
+    color_reset=
+    bold_text=
+    color_red=
+#    color_green=
+    color_yellow=
+#    color_blue=
+#    color_magenta=
+#    color_cyan=
+#    color_white=
+
+fi
+
+#------------------------------------------------------------------------------
+
+print_error ()
+## prints custom heading and error message without exiting the script; in color, if available
+# expected arguments:
+# $1 = error heading (string)
+# $2 = error message (string)
+{
+    # check if exactly 2 non-empty arguments have been passed
+    # if not, print out an input check error without colors
+    if [ $# -ne 2 ] || [ -z "$1" ] || [ -z "$2" ]; then
+        # $1 and $2 are to be shown literally in this message
+        # link to wiki: https://github.com/koalaman/shellcheck/wiki/SC2016
+        # shellcheck disable=SC2016
+        printf 'print_error() input check\n\nWrong number or empty arguments have been passed to the function: %s\n\nExpected the following 2:\n$1 - error heading\n$2 - error message\n' $#
+        return 1
+    fi
+
+    error_heading=$1; error_message=$2
+
+    printf '%b\n\n%b\n\n%b\n' \
+        "Error heading: ${color_yellow}${error_heading}${color_reset}" \
+        "Error message: ${error_message}" \
+        "${color_red}Fatal error occurred.${color_reset}"
+} >&2
+
+print_error_and_exit_script ()
+## direcly uses print_error, but this one exits the script with customizable exit code (optional 3rd argument)
+# expected arguments:
+# $1 = error heading (string)
+# $2 = error message (string)
+# $3 = return code (number) - optional, if not given, 1 is used
+{
+    # check if 2 (or 3) non-empty arguments have been passed
+    # if not, print out an input check error without colors
+    if { [ $# -ne 2 ] && [ $# -ne 3 ]; } || [ -z "$1" ] || [ -z "$2" ]; then
+        # $1, $2, $3 are to be shown literally in this message
+        # link to wiki: https://github.com/koalaman/shellcheck/wiki/SC2016
+        # shellcheck disable=SC2016
+        printf 'print_error_and_exit_script() input check\n\nWrong number or empty arguments have been passed to the function: %s\n\nExpected the following 2 or 3:\n$1 - error heading (string)\n$2 - error message (string)\n$3 - return code (number) - optional, if not given, 1 is used\n' $#
+        return 1
+    fi
+
+    if [ $# -eq 2 ] || [ -z "$3" ]; then
+        return_code=1
+    elif [ -n "$3" ] && ! [ "$3" -eq "$3" ] 2> /dev/null; then
+        printf 'print_error_and_exit_script() input check\n\nThird argument is expected to be a return code, i.e. a number.\nBut something else was passed instead: %s\n' "$3"
+        return 1
+    else
+        return_code=$3
+    fi
+
+    print_error "$1" "$2"
+
+    exit "$return_code"
+
+} >&2
+
+#------------------------------------------------------------------------------
+
+# shellcheck disable=SC2120
+is_user_root ()
+## this is the only POSIX-ly correct way to find out if the user is root
+{
+    if [ $# -ne 0 ]; then
+        print_error "is_user_root() input check" "Some arguments have been passed to the function!\\nNo arguments expected.\\nPassed: $*"
+    fi
+
     [ "$(id -u)" -eq 0 ]
 }
 
@@ -89,22 +136,26 @@ am_i_root()
 # in this function call, the SC2119 information is irrelevant and safe to ignore
 # link to wiki: https://github.com/koalaman/shellcheck/wiki/SC2119
 # shellcheck disable=SC2119
-am_i_root && print_error_and_exit "am_i_root() function call" "Running this script with root privileges is not allowed!"
+if is_user_root; then
+    print_error_and_exit_script 'is_user_root()' "Running this script with root privileges is not allowed!"
+fi
 
 #------------------------------------------------------------------------------
 
-check_for_prerequisites()
+check_for_prerequisites ()
 # expected arguments:
 # any number of program names; at least one
 {
     # check if no argument has been passed
-    [ "${#}" -eq 0 ] && print_error_and_exit "check_for_prerequisites() input check" "No arguments have been passed to the function!\\n\\tAt least one program name expected."
-
+    if [ $# -eq 0 ]; then
+        print_error_and_exit_script 'check_for_prerequisites() input check' "No arguments have been passed to the function! At least one program name expected."
+    fi
     # iterate through the given arguments
-    while [ "${#}" -gt 0 ]
-    do
+    while [ $# -gt 0 ]; do
         # check if the argument is a program which is installed
-        command -v "${1}" > /dev/null 2>&1 || print_error_and_exit "check_for_prerequisites() runtime" "This script requires '${1}' but it is not available on this system!\\n\\tPlease install the corresponding package manually."
+        if ! command -v "$1" > /dev/null 2>&1; then
+            print_error_and_exit_script 'check_for_prerequisites()' "This script requires '$1' but it is not available on this system! Please install the corresponding package manually."
+        fi
         # move to the next argument
         shift
     done
@@ -114,32 +165,40 @@ check_for_prerequisites xdotool pgrep
 
 #------------------------------------------------------------------------------
 
-is_number()
+is_number ()
 # expected arguments:
 # $1 = variable or literal
 {
     # check if exactly one argument has been passed
-    [ "${#}" -eq 1 ] || print_error_and_exit "is_number() input check" "Exactly one argument has not been passed to the function!\\n\\tOne variable or literal to test expected.\\n\\tPassed: ${*}"
+    if [ $# -ne 1 ]; then
+        print_error_and_exit_script 'is_number() input check' "Exactly one argument has not been passed to the function!One variable or literal to test expected.\\nPassed: $*"
+    fi
 
     # check if the argument is an integer number
     # this will return an exit code of the command itself directly
-    [ "${1}" -eq "${1}" ] 2> /dev/null
+    [ "$1" -eq "$1" ] 2> /dev/null
 }
 
 #------------------------------------------------------------------------------
 
-print_usage_and_exit()
+print_usage_and_exit ()
 # expected arguments:
 # $1 = exit code
 {
     # check if exactly one argument has been passed
-    [ "${#}" -eq 1 ] || print_error_and_exit "print_usage_and_exit() input check" "Exactly one argument has not been passed to the function!\\n\\tPassed: ${*}"
+    if [ $# -ne 1 ]; then
+        print_error_and_exit_script 'print_usage_and_exit() input check' "Exactly one argument has not been passed to the function!\\nPassed: $*"
+    fi
 
     # check if the argument is a number
-    is_number "${1}" || print_error_and_exit "print_usage_and_exit() input check" "The argument is not a number!\\n\\tExpected an exit code from the script.\\n\\tPassed: ${1}"
+    if ! is_number "$1"; then
+        print_error_and_exit_script 'print_usage_and_exit() input check' "The argument is not a number! Expected an exit code from the script.\\nPassed: $1"
+    fi
 
     # in case of non-zero exit code given, redirect all output to stderr
-    [ "${1}" -ne 0 ] && exec 1>&2
+    if [ "$1" -ne 0 ]; then
+        exec >&2
+    fi
 
     printf 'Script  : %s\n' "${script_name_human_friendly}"
     printf 'Version : %s\n' "${script_version}"
@@ -151,65 +210,77 @@ print_usage_and_exit()
     printf '\t\tFor the left Control key and the Print Screen key:\n'
     printf '\t\t"Control_L+Print"\n'
 
-    exit "${1}"
+    exit "$1"
 }
 
 #------------------------------------------------------------------------------
 
 # process arguments given to the script
-while getopts ":hk:" option
-do
-    case "${option}" in
-        k)
-            hotkey=${OPTARG}
-            ;;
-        h)
-            print_usage_and_exit 0
-            ;;
-        *)
-            print_usage_and_exit 1
-            ;;
+while getopts ":hk:" cli_option; do
+    case "${cli_option}" in
+        ( k ) hotkey=${OPTARG}
+        break
+        ;;
+        ( h ) print_usage_and_exit 0
+        break
+        ;;
+        ( * ) print_usage_and_exit 1
+        break
+        ;;
     esac
 done
 shift $(( OPTIND - 1 ))
 
 #------------------------------------------------------------------------------
 
-get_process_id()
+get_process_id ()
 # expected arguments:
 # $1 = process name
 {
     # check if exactly one argument has been passed
-    [ "${#}" -eq 1 ] || print_error_and_exit "get_process_id() input check" "Exactly one argument has not been passed to the function!\\n\\tPassed: ${*}"
+    if [ $# -ne 1 ]; then
+        print_error_and_exit_script "get_process_id() input check" "Exactly one argument has not been passed to the function!\\nPassed: $*"
+    fi
 
     # check if the argument is an empty string
-    [ -n "${1}" ] || print_error_and_exit "get_process_id() input check" "The argument is an empty string!\\n\\tExpected a process name."
+    if [ -z "$1" ]; then
+        print_error_and_exit_script "get_process_id() input check" "The argument is an empty string! Expected a process name."
+    fi
 
     # try to get the process id using the process name
-    pgrep "${1}" | head -n 1
+    pgrep "$1" | head -n 1
 }
 
 #------------------------------------------------------------------------------
 
-get_window_id()
+get_window_id ()
 # expected arguments:
 # $1 = process id
 # $2 = window name
 {
     # check if exactly two arguments have been passed
-    [ "${#}" -eq 2 ] || print_error_and_exit "get_window_id() input check" "Exactly two arguments have not been passed to the function!\\n\\tExpected a process id and a window name.\\n\\tPassed: ${*}"
+    if [ $# -ne 2 ]; then
+        print_error_and_exit_script "get_window_id() input check" "Exactly two arguments have not been passed to the function! Expected a process id and a window name.\\nPassed: $*"
+    fi
 
     # check if the first argument is a number
-    is_number "${1}" || print_error_and_exit "get_window_id() input check" "The first argument is not a number!\\n\\tExpected a process id.\\n\\tPassed: ${1}"
+    if ! is_number "$1"; then
+        print_error_and_exit_script "get_window_id() input check" "The first argument is not a number! Expected a process id.\\nPassed: $1"
+    fi
 
-    [ -n "${2}" ] || print_error_and_exit "get_window_id() input check" "The second argument is an empty string!\\n\\tExpected a window name."
+    # check if the second argument is an empty string
+    if [ -z "$2" ]; then
+        print_error_and_exit_script "get_window_id() input check" "The second argument is an empty string! Expected a window name."
+    fi
 
     # try to get the window id using the process id and the window name
-        #--all   : Require that all conditions be met.
-        #--limit : Stop searching after finding N matching windows.
-        #--pid   : Match windows that belong to a specific process id.
-        #--name  : Match against the window name. This is the same string that is displayed in the window titlebar.
-    xdotool search --all --limit 1 --pid "${1}" --name "${2}" || print_error_and_exit "get_window_id() runtime" "No window matching process id '${1}' and window name '${2}' has been found."
+        # --all   : Require that all conditions be met.
+        # --limit : Stop searching after finding N matching windows.
+        # --pid   : Match windows that belong to a specific process id.
+        # --name  : Match against the window name. This is the same string that is displayed in the window titlebar.
+    if ! xdotool search --all --limit 1 --pid "$1" --name "$2"; then
+        print_error_and_exit_script 'get_window_id()' "No window matching process id '$1' and window name '$2' has been found."
+    fi
 }
 
 #------------------------------------------------------------------------------
@@ -217,8 +288,19 @@ get_window_id()
 # here comes the core part,
 # an actual use of the above generic functions
 
+# try to get the Lightshot process id
+lightshot_process_id=$( get_process_id Lightshot.exe )
+
+if ! is_number "${lightshot_process_id}"; then
+    print_error_and_exit_script "is_number \${lightshot_process_id}" "Lightshot process is not running."
+fi
+
 # try to get the Lightshot window id
-lightshot_window_id=$(get_window_id "$(get_process_id Lightshot.exe)" Lightshot) || print_error_and_exit "CRITICAL ERROR" "Lightshot.exe process is probably not running."
+lightshot_window_id=$( get_window_id "${lightshot_process_id}" Lightshot )
+
+if ! is_number "${lightshot_window_id}"; then
+    print_error_and_exit_script "is_number \${lightshot_window_id}" "Lightshot process is running but window not found."
+fi
 
 # simulate the pre-defined print screen hotkey on the Lightshot window
 xdotool key --window "${lightshot_window_id}" "${hotkey}"
